services:
  claude-review:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SHELL=/bin/bash
      - REPO_URL=https://github.com/arandaschimpf/claude-review.git
    env_file:
      - .env
    volumes:
      - claude_auth:/home/claude/.claude
    stdin_open: true
    tty: true

volumes:
  claude_auth: